In [7]:
#for each document in training set create as frequency matrix for these
#words in dicitionary & corresponding labels
import os
import numpy as np
from sklearn.datasets import make_classification
from collections import Counter
def make_Dictionary(root_dir):
    all_words=[]
    emails=[os.path.join(root_dir,f)
           for f in os.listdir(root_dir)]
    for mail in emails:
        with open(mail) as m:
            for line in m:
                words=line.split()
                all_words += words
    dictionary=Counter(all_words)
    list_to_remove=list(dictionary)
    
    for item in list_to_remove:
    #TO REMOVE NUMERICAL VALUES
        if item.isalpha()==False:
            del dictionary[item]
        elif len(item)==1:
            del dictionary[item]
        dictionary=dictionary.most_common(3000)
        return dictionary

TRAIN_DIR="/home/root1234/Documents/train-mails"    
TEST_DIR ="/home/root1234/Documents/test-mails"
dictionary=make_Dictionary(TRAIN_DIR)
print(dictionary)

[('_', 33614), ('.', 28762), ('-', 19221), (',', 18425), ('*', 17704), ('=', 8874), ('!', 5925), (':', 5209), ('/', 4903), (')', 4633), ('"', 4444), ('$', 4200), ("'", 4131), ('(', 3928), ('0', 1978), ('+', 1883), ('20', 1764), ('>', 1619), ('~', 1617), ('order', 1414), ("'s", 1356), ('#', 1325), ('address', 1299), ('report', 1217), ('?', 1154), ('mail', 1133), ('language', 1099), ('send', 1080), ('email', 1066), ('1', 1029), (';', 1025), ('program', 1009), ('our', 991), ('list', 946), ('one', 921), ('name', 883), ('2', 873), ('receive', 826), ('free', 801), ('money', 797), ('@', 757), ('work', 756), ("n't", 740), ('3d', 736), ('5', 696), ('information', 684), ('business', 669), ('please', 657), ('3', 640), ('university', 600), ('e-mail', 598), ('s', 584), ('e', 568), ('us', 567), ('day', 559), ('10', 550), ('follow', 545), ('internet', 533), ('\\', 529), ('over', 514), ('4', 502), ('call', 488), ('http', 479), ('check', 475), ('each', 466), ('linguistic', 460), ('include', 452), ('com

In [2]:
def extract_features(mail_dir):
    files=[os.path.join(mail_dir,fi) for fi in os.listdir(mail_dir)]
    features_matrix=np.zeros((len(files),3000))
    train_labels=np.zeros(len(files))
    count=0;
    docID=0;
    for fil in files:
        with open(fil) as fi:
            for i,line in enumerate(fi):
                if i==2:
                    words=line.split()
                    for word in words:
                        wordID=0
                        for i,d in enumerate(dictionary):
                            if d[0]==word:
                                wordID=i
                                features_matrix[docID,wordID]=words.count(word)
            train_labels[docID]=0
            filepathTokens=fil.split('/')
            lastToken=filepathTokens[len(filepathTokens)-1]
            if lastToken.startswith("spmsg"):
                train_labels[docID]=1
                count=count+1
            docID=docID+1
    return features_matrix,train_labels

TRAIN_DIR="/home/root1234/Documents/train-mails"    
TEST_DIR ="/home/root1234/Documents/test-mails"
features_matrix,labels=extract_features(TRAIN_DIR)
print(features_matrix,labels)

[[ 0.  6.  6. ...  0.  0.  0.]
 [ 2.  5.  0. ...  0.  0.  0.]
 [ 0.  9. 35. ...  0.  0.  0.]
 ...
 [ 0.  4.  1. ...  0.  0.  0.]
 [ 0.  8.  0. ...  0.  0.  0.]
 [ 0.  7.  1. ...  0.  0.  0.]] [0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1.
 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1.
 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1.
 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1.
 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0.
 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0.
 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1.
 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 1.
 0. 1

In [6]:
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_classification
TRAIN_DIR="/home/root1234/Documents/train-mails"    
TEST_DIR ="/home/root1234/Documents/test-mails"
dictionary=make_Dictionary(TRAIN_DIR)
print("reading and processing emails from file.")

#creating train data set
features_matrix,labels=extract_features(TRAIN_DIR)
#creating test data
test_feature_matrix,test_labels=extract_features(TEST_DIR)

#Random Forest Classifier Model
model=RandomForestClassifier()
print("Training model")
#TRAIN MODEL
model.fit(features_matrix,labels)
predicted_lables=model.predict(test_feature_matrix)
print("FINISHED classifying.accuracy score:")
print(accuracy_score(test_labels,predicted_lables))

reading and processing emails from file.


NameError: name 'RandomForestClassifier' is not defined